
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          #- not_null
          # - accepted_values:
          #     values: [1,2,3]
          #     quote: false

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
        
          - relationships:
              to: ref('my_first_dbt_model')
              field: id


  - name: playing_with_tests
    description: "Snowflake data"
    columns:
      - name : C_CUSTKEY
        data_tests:
          - not_null
          - unique
      - name : c_mktsegment
        data_tests:
          - accepted_values:
              values: ["BUILDING", "AUTOMOBILE", "MACHINERY", "HOUSEHOLD", "FURNITURE"]
              quote: True

  - name: snowflake_customer_purchases
    description: "The total purchases for each customer in sample data."
    columns :
        - name: cust_key
          data_tests:
            -  unique
            -  not_null

  - name : cummulative_orders_by_data
    description: "Cumm orders"
    columns:
      - name: o_orderdate
        data_tests:
          - not_null

  - name : dates
